name: cpm
description: Cinema Project Manager is a tool to efficiently manage the production of a cinema project.
repository: https://github.com/studiorvandco/cpm_app
documentation: https://github.com/studiorvandco/cpm_app/wiki

version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.2
  cupertino_icons: ^1.0.6
  dynamic_color: ^1.6.7
  equatable: ^2.0.5
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  go_router: ^11.1.2
  hooks_riverpod: ^2.4.3
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.1
  json_cache: ^3.0.1
  locale_names: ^1.1.1
  localstorage: ^4.0.1+4
  maps_launcher: ^2.2.0
  package_info_plus: ^4.1.0
  path: ^1.8.3
  riverpod_annotation: ^2.1.1
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.0
  simple_icons: ^7.10.0
  supabase_flutter: ^1.10.7
  syncfusion_flutter_calendar: ^22.1.37
  url_launcher: ^6.1.12
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  lint: ^2.1.2
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/logos/
