name: cpm
description: Cinema Project Manager is a tool to efficiently manage the production of a cinema project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  intl: ^0.18.0
  url_launcher: ^6.1.11
  maps_launcher: ^2.2.0
  file_picker: ^5.3.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  yaml: ^3.1.2
  easy_localization: ^3.0.2
  easy_logger: ^0.0.2
  msix: ^3.12.3
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_native_splash: ^2.3.0
  flutter_staggered_grid_view: ^0.6.2
  syncfusion_flutter_calendar: ^21.2.5
  json_annotation: ^4.8.1
  flutter_secure_storage: ^8.0.0

  calendar_view: ^1.0.3 # TODO: remove

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  riverpod_generator: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  dart_code_metrics: ^5.7.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/logos/
    - assets/translations/

msix_config:
  display_name: Cinema Project Manager
  publisher_display_name: Studio Rv & Co
  identity_name: rvandco.cpm
  logo_path: assets\images\logo-cpm-white-alpha.png