name: Build

on:
  push:
    branches:
      - main
      - release

jobs:
  build_android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: echo "${{ vars.CPM_CONFIG }}" > assets/config/config.yaml
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: Android
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Retrieve Release Version
        id: versionstep
        run: |
          VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2)
          echo "::set-output name=VERSION::$VERSION"
      - name: Upload the APK onto Github
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/flutter-apk/app-release.apk'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.versionstep.outputs.VERSION }}
  
  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: echo "${{ vars.CPM_CONFIG }}" > assets/config/config.yaml
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: build/windows/runner/Release
      - run: mkdir setup
      - uses: caphyon/advinst-github-action@v1.0
        with:
          aip-path: 'Cinema Project Manager.aip'
          aip-build-name: 'DefaultBuild'
          aip-package-name: 'cpm.msi'
      - uses: actions/upload-artifact@v3
        with:
          name: Windows (MSI)
          path: ${{ github.workspace }}/setup/cpm.msi
  
  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          sudo apt-get install -y libsecret-1-dev libjsoncpp-dev
      - run: echo "${{ vars.CPM_CONFIG }}" > assets/config/config.yaml
      - run: flutter build linux --release
      - run: tree build/linux
      - uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: build/linux/x64/release/bundle
  
  build_web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: echo "${{ vars.CPM_CONFIG }}" > assets/config/config.yaml
      - run: flutter build web --release
      - uses: actions/upload-artifact@v3
        with:
          name: Web
          path: web