name: Build

on:
  push:
    branches:
      - main
      - develop
      - build

permissions: read-all

jobs:
  build_android:
    name: Build (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          flutter pub get
          flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: cpm_android.apk
          path: build/app/outputs/flutter-apk/app-release.apk