name: Build | Release

on:
  push:
    branches:
      - main
      - release

jobs:
  build_android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Add config
        run: echo "${{ vars.CPM_CONFIG }}" > assets/config/config.yaml
      - name: Build app
        run: flutter build apk --release
      - name: Read version
        run: |
          VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2)
          echo "version=$VERSION" >> "$GITHUB_ENV"
      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/CPM.apk
      - name: Upload to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/flutter-apk/CPM.apk'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.version }}

  build_ios:
    name: iOS
    runs-on: macos-latest
    # TODO: build and release
  
  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Add config
        run: echo "${{ vars.CPM_CONFIG }}" > assets/config/config.yaml
      - name: Build app
        run: flutter build windows --release
      - run: mkdir setup
      - name: Build MSI
        uses: caphyon/advinst-github-action@v1.0
        with:
          aip-path: 'Cinema Project Manager.aip'
          aip-build-name: 'DefaultBuild'
          aip-package-name: 'CPM.msi'
      - name: Read version
        run: |
          VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2)
          echo "version=$VERSION" >> "$GITHUB_ENV"
      - name: Upload to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ github.workspace }}/setup/CPM.msi'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.version }}
  
  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install required packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          sudo apt-get install -y libsecret-1-dev libjsoncpp-dev
      - name: Add config
        run: echo "${{ vars.CPM_CONFIG }}" > assets/config/config.yaml
      - name: Build app
        run: flutter build linux --release
      - name: Upload to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: build/linux/x64/release/bundle
      # TODO: release

  build_macos:
    name: MacOS
    runs-on: macos-latest
    # TODO: build and release

  build_web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Add config
        run: echo "${{ vars.CPM_CONFIG }}" > assets/config/config.yaml
      - name: Build app
        run: flutter build web --release
      - name: Upload to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Web
          path: web
      # TODO: release